export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_USER_FAVS = "SET_CURRENT_USER_FAVS";
export const SET_CURRENT_USER_UNFAVS = "SET_CURRENT_USER_UNFAVS";

export const CHATROOM_LOADING = "CHATROOM_LOADING";
export const GET_CHATROOMS = "GET_CHATROOMS";
export const GET_CHATROOM = "GET_CHATROOM";
export const ADD_CHATROOM = "ADD_CHATROOM";
export const DELETE_CHATROOM = "DELETE_CHATROOM";
